// <auto-generated />
using System;
using MauiLib3._1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drink.Infrastructure.Migrations
{
    [DbContext(typeof(CoffeContext))]
    partial class CoffeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("MauiLib3._1.Models.DrinkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MauiLib3._1.Models.EspressoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coffee")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmallCup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.ToTable("Espressos", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MauiLib3._1.Models.CocoaModel", b =>
                {
                    b.HasBaseType("MauiLib3._1.Models.DrinkModel");

                    b.Property<int>("CocoaPowder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Milk")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cocoas", (string)null);
                });

            modelBuilder.Entity("MauiLib3._1.Models.CappuccinoModel", b =>
                {
                    b.HasBaseType("MauiLib3._1.Models.EspressoModel");

                    b.Property<int>("MediumCup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Milk")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cappuccinos", (string)null);
                });

            modelBuilder.Entity("MauiLib3._1.Models.RafModel", b =>
                {
                    b.HasBaseType("MauiLib3._1.Models.CappuccinoModel");

                    b.Property<int>("Cream")
                        .HasColumnType("INTEGER");

                    b.ToTable("Rafs", (string)null);
                });

            modelBuilder.Entity("MauiLib3._1.Models.EspressoModel", b =>
                {
                    b.HasOne("MauiLib3._1.Models.DrinkModel", "Drink")
                        .WithMany("Espressos")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("MauiLib3._1.Models.CocoaModel", b =>
                {
                    b.HasOne("MauiLib3._1.Models.DrinkModel", null)
                        .WithOne()
                        .HasForeignKey("MauiLib3._1.Models.CocoaModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MauiLib3._1.Models.CappuccinoModel", b =>
                {
                    b.HasOne("MauiLib3._1.Models.EspressoModel", null)
                        .WithOne()
                        .HasForeignKey("MauiLib3._1.Models.CappuccinoModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MauiLib3._1.Models.RafModel", b =>
                {
                    b.HasOne("MauiLib3._1.Models.CappuccinoModel", null)
                        .WithOne()
                        .HasForeignKey("MauiLib3._1.Models.RafModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MauiLib3._1.Models.DrinkModel", b =>
                {
                    b.Navigation("Espressos");
                });
#pragma warning restore 612, 618
        }
    }
}
